package com.safepulse.domain.journey

enum class TransitionType {
    JOURNEY_STARTED,
    WALKING_STARTED,
    WALKING_STOPPED,
    VEHICLE_ENTERED,
    VEHICLE_EXITED,
    TRAIN_LIKELY_DETECTED,
    STATION_EXIT_DETECTED,
    CAB_PICKUP_DETECTED,
    CAB_DROP_DETECTED,
    LAST_MILE_WALK_STARTED,
    HIGH_RISK_ZONE_ENTERED,
    HIGH_RISK_ZONE_EXITED,
    UNEXPECTED_STOP,
    DESTINATION_REACHED
}
